const fs = require('fs');
const path = require('path');

const ENV_PATH = path.join(__dirname, '../../.env');

/**
 * Parses the homeserver .env configuration file into a key-value object.
 * Adheres to Single Responsibility Principle (SRP) for config parsing.
 * @returns {Object} Key-value pairs representing configurations
 */
function parseEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const content = fs.readFileSync(ENV_PATH, 'utf-8');
  const config = {};
  content.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#') && line.includes('=')) {
      const idx = line.indexOf('=');
      const key = line.substring(0, idx).trim();
      const val = line.substring(idx + 1).trim();
      config[key] = val;
    }
  });
  return config;
}

/**
 * Serializes and writes key-value configuration overrides to the .env file.
 * Preserves the file integrity.
 * @param {Object} config Key-value config dictionary to save
 */
function writeEnv(config) {
  let content = '# Homeserver Configurations (Autogenerated via WebUI)\n';
  for (const [key, val] of Object.entries(config)) {
    content += `${key}=${val}\n`;
  }
  fs.writeFileSync(ENV_PATH, content, 'utf-8');
}

module.exports = {
  parseEnv,
  writeEnv,
  ENV_PATH
};
