const http = require('http');
const fs = require('fs');
const path = require('path');
const { spawn, exec } = require('child_process');

const isMac = process.platform === 'darwin';

// Helper to spawn setup.sh script (bypasses sudo on macOS for dev environments)
function spawnSetup(args, options = {}) {
  const scriptPath = path.join(__dirname, '../setup.sh');
  const cmd = isMac ? 'bash' : 'sudo';
  const spawnArgs = isMac ? [scriptPath, ...args] : ['bash', scriptPath, ...args];
  return spawn(cmd, spawnArgs, options);
}

const PORT = 8888;
const ENV_PATH = path.join(__dirname, '../.env');

// Helper to parse .env file
function parseEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const content = fs.readFileSync(ENV_PATH, 'utf-8');
  const config = {};
  content.split('\n').forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#') && line.includes('=')) {
      const idx = line.indexOf('=');
      const key = line.substring(0, idx).trim();
      const val = line.substring(idx + 1).trim();
      config[key] = val;
    }
  });
  return config;
}

// Helper to write .env file
function writeEnv(config) {
  let content = '# Homeserver Configurations (Autogenerated via WebUI)\n';
  for (const [key, val] of Object.entries(config)) {
    content += `${key}=${val}\n`;
  }
  fs.writeFileSync(ENV_PATH, content, 'utf-8');
}

const server = http.createServer((req, res) => {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  // Serve Frontend
  if (req.url === '/' || req.url === '/index.html') {
    const indexPath = path.join(__dirname, 'index.html');
    if (fs.existsSync(indexPath)) {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(fs.readFileSync(indexPath));
    } else {
      res.writeHead(404);
      res.end('index.html not found');
    }
    return;
  }

  // API: Get Status
  if (req.url === '/api/status' && req.method === 'GET') {
    if (isMac) {
      const containers = {
        media_jellyfin: 'running',
        media_qbittorrent: 'running',
        immich_server: 'running',
        nextcloud_app: 'running',
        utility_vaultwarden: 'running',
        media_radarr: 'running',
        media_sonarr: 'running',
        media_prowlarr: 'running',
        utility_tailscale: 'running'
      };
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(jsonString({ containers }));
      return;
    }
    // Run docker ps -a to see container states
    exec('docker ps -a --format "{{.Names}}:{{.State}}"', (err, stdout, stderr) => {
      if (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(jsonString({ error: err.message }));
        return;
      }
      const containers = {};
      stdout.split('\n').forEach(line => {
        const parts = line.trim().split(':');
        if (parts.length === 2) {
          containers[parts[0]] = parts[1];
        }
      });
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(jsonString({ containers }));
    });
    return;
  }

  // API: Get Config
  if (req.url === '/api/config' && req.method === 'GET') {
    const config = parseEnv();
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(jsonString(config));
    return;
  }

  // API: Save Config
  if (req.url === '/api/config' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try {
        const config = JSON.parse(body);
        const existing = parseEnv();
        const updated = { ...existing, ...config };
        writeEnv(updated);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(jsonString({ success: true }));
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(jsonString({ error: 'Invalid JSON' }));
      }
    });
    return;
  }

  // API: Get Samba Info
  if (req.url === '/api/samba' && req.method === 'GET') {
    const child = spawnSetup(['--samba-info'], {
      cwd: path.join(__dirname, '..')
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', data => { stdout += data.toString(); });
    child.stderr.on('data', data => { stderr += data.toString(); });
    child.on('close', code => {
      if (code === 0) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(stdout);
      } else {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: stderr || `Samba info exited with code ${code}` }));
      }
    });
    return;
  }

  // API: Samba Actions
  if (req.url === '/api/samba/action' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try {
        const payload = JSON.parse(body);
        const { action, username, password, share_name, share_path, valid_users, guest_ok, read_only } = payload;
        
        let args = [];
        if (action === 'install') {
          args = ['--install-samba'];
        } else if (action === 'add-user') {
          args = ['--samba-add-user', username, password];
        } else if (action === 'remove-user') {
          args = ['--samba-remove-user', username];
        } else if (action === 'add-share') {
          args = ['--samba-add-share', share_name, share_path, valid_users, guest_ok, read_only];
        } else if (action === 'remove-share') {
          args = ['--samba-remove-share', share_name];
        } else {
          res.writeHead(400, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ error: 'Invalid Samba action' }));
          return;
        }

        const child = spawnSetup(args, {
          cwd: path.join(__dirname, '..')
        });

        let stdout = '';
        let stderr = '';
        child.stdout.on('data', data => { stdout += data.toString(); });
        child.stderr.on('data', data => { stderr += data.toString(); });
        child.on('close', code => {
          if (code === 0) {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ success: true, output: stdout }));
          } else {
            res.writeHead(500, { 'Content-Type': 'application/json' });
            res.end(JSON.stringify({ error: stderr || `Samba action exited with code ${code}` }));
          }
        });
      } catch (err) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON payload' }));
      }
    });
    return;
  }

  // API: Get Netplan Info
  if (req.url === '/api/netplan' && req.method === 'GET') {
    const child = spawnSetup(['--netplan-info'], {
      cwd: path.join(__dirname, '..')
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', data => { stdout += data.toString(); });
    child.stderr.on('data', data => { stderr += data.toString(); });
    child.on('close', code => {
      if (code === 0) {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(stdout);
      } else {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: stderr || `Netplan info exited with code ${code}` }));
      }
    });
    return;
  }

  // API: Container Logs Stream (SSE)
  if (req.url.startsWith('/api/logs') && req.method === 'GET') {
    const parsedUrl = new URL(req.url, `http://${req.headers.host}`);
    const service = parsedUrl.searchParams.get('service');
    if (!service) {
      res.writeHead(400);
      res.end('Missing service parameter');
      return;
    }

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive'
    });

    res.write(`data: [Streaming real-time logs for container: ${service}]\n\n`);

    const child = spawn('docker', ['logs', '-f', '--tail', '200', service]);

    child.stdout.on('data', data => {
      const lines = data.toString().split('\n');
      lines.forEach(line => {
        if (line.trim()) {
          const cleaned = line.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
          res.write(`data: ${cleaned}\n\n`);
        }
      });
    });

    child.stderr.on('data', data => {
      const lines = data.toString().split('\n');
      lines.forEach(line => {
        if (line.trim()) {
          const cleaned = line.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
          res.write(`data: ${cleaned}\n\n`);
        }
      });
    });

    child.on('close', code => {
      res.write(`data: [Log stream finished with code ${code}]\n\n`);
      res.end();
    });

    req.on('close', () => {
      child.kill();
    });

    return;
  }

  // API: Logs Stream (SSE)
  if (req.url.startsWith('/api/run') && req.method === 'GET') {
    const parsedUrl = new URL(req.url, `http://${req.headers.host}`);
    const action = parsedUrl.searchParams.get('action');
    const services = parsedUrl.searchParams.get('services') || '';

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive'
    });

    res.write('data: Starting task...\n\n');

    let args = [];
    let env = { ...process.env, NON_INTERACTIVE: 'true' };

    if (action === 'nuke') {
      args = ['--nuke', services || 'all'];
    } else if (action === 'update') {
      args = ['--update', services || 'all'];
    } else if (action === 'reconfigure') {
      args = ['--reconfigure', services || 'all'];
    } else if (action === 'restart') {
      args = ['--restart', services || 'all'];
    } else if (action === 'prune') {
      args = ['--prune'];
    } else if (action === 'homepage') {
      args = ['--homepage'];
    } else if (action === 'backup') {
      args = ['--backup'];
    } else if (action === 'tailscale') {
      args = ['--tailscale'];
    } else if (action === 'samba') {
      args = ['--install-samba'];
    } else if (action === 'maintenance') {
      args = ['--sys-maintenance'];
    } else if (action === 'git-push') {
      args = ['--git-push'];
    } else if (action === 'sync') {
      args = ['--sync'];
    } else if (action === 'install-docker') {
      args = ['--install-docker'];
    } else if (action === 'check-updates') {
      args = ['--check-updates'];
    } else if (action === 'netplan-static') {
      const iface = parsedUrl.searchParams.get('iface') || '';
      const ip = parsedUrl.searchParams.get('ip') || '';
      const gw = parsedUrl.searchParams.get('gw') || '';
      const dns1 = parsedUrl.searchParams.get('dns1') || '';
      const dns2 = parsedUrl.searchParams.get('dns2') || '';
      args = ['--set-static-ip', iface, ip, gw, dns1, dns2];
    } else if (action === 'netplan-dhcp') {
      const iface = parsedUrl.searchParams.get('iface') || '';
      args = ['--set-dhcp', iface];
    } else {
      res.write('data: Unknown action.\n\n');
      res.end();
      return;
    }

    const child = spawnSetup(args, {
      cwd: path.join(__dirname, '..'),
      env: env
    });

    child.stdout.on('data', data => {
      const lines = data.toString().split('\n');
      lines.forEach(line => {
        if (line.trim()) {
          const cleaned = line.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
          res.write(`data: ${cleaned}\n\n`);
        }
      });
    });

    child.stderr.on('data', data => {
      const lines = data.toString().split('\n');
      lines.forEach(line => {
        if (line.trim()) {
          const cleaned = line.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
          res.write(`data: [ERROR] ${cleaned}\n\n`);
        }
      });
    });

    child.on('close', code => {
      res.write(`data: Task finished with exit code ${code}\n\n`);
      res.end();
    });

    req.on('close', () => {
      child.kill();
    });

    return;
  }

  // 404
  res.writeHead(404);
  res.end('Not Found');
});

function jsonString(obj) {
  return JSON.stringify(obj, null, 2);
}

server.listen(PORT, () => {
  console.log(`Homeserver WebUI server running at http://localhost:${PORT}`);
});
